[package]
name = "pick"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.version = "0.15.0-dev"
iced.features = ["tokio", "sipper", "markdown", "canvas", "highlighter"]

serde.version = "1"
serde.features = ["derive"]

similar.version = "3"
similar.features = ["inline"]

tokio.version = "1"
tokio.features = ["fs", "macros", "process", "sync", "test-util"]

tracing-subscriber.version = "0.3"
tracing-subscriber.features = ["tracing-log"]

function = "0.3"
log = "0.4"
reason = "0.2.0-dev"
serde_json = "1"
sipper = "0.2"

[lints.clippy]
large-enum-variant = "allow"
type-complexity = "allow"

[patch.crates-io]
cosmic-text.git = "https://github.com/hecrj/cosmic-text.git"
cosmic-text.rev = "6e10ac2ce889f48c9eeb1f19c1340a37d6afae31"

iced.git = "https://github.com/iced-rs/iced.git"
iced.rev = "423a6c795f24846b8454a918710799ab5bb4d555"

reason.git = "https://github.com/hecrj/reason.git"
reason.rev = "9d3a1f54afb345f9bdc6fc3b5e016b88bda62b71"

# iced.path = "../iced"
# reason.path = "../reason"
