[package]
name = "pick"
version = "0.1.0-dev"
edition = "2024"

[workspace]
members = ["core", "test"]

[dependencies]
pick-core = { version = "0.1.0-dev", path = "./core" }

function = "0.3"
iced_palace = "0.15.0-dev"
log = "0.4"
reason = "0.2.0-dev"
serde_json = "1"
sipper = "0.2"

iced.version = "0.15.0-dev"
iced.features = ["tokio", "sipper", "markdown", "canvas", "highlighter"]

serde.version = "1"
serde.features = ["derive"]

similar.version = "3"
similar.features = ["inline"]

tokio.version = "1"
tokio.features = ["fs", "process", "sync"]

tracing-subscriber.version = "0.3"
tracing-subscriber.features = ["tracing-log"]

[dev-dependencies]
pick-test = { version = "0.1.0-dev", path = "./test" }

tokio.version = "1"
tokio.features = ["macros", "test-util"]

[lints.clippy]
large-enum-variant = "allow"
type-complexity = "allow"

[patch.crates-io]
decoder.git = "https://github.com/hecrj/decoder.git"
decoder.rev = "c2b759faa6cc49a4fd25271c7149028e6ff395c3"

iced.git = "https://github.com/iced-rs/iced.git"
iced.rev = "9efcdf274c35f1ae69d29bd35f43acb9363a0a97"

iced_core.git = "https://github.com/iced-rs/iced.git"
iced_core.rev = "9efcdf274c35f1ae69d29bd35f43acb9363a0a97"

iced_widget.git = "https://github.com/iced-rs/iced.git"
iced_widget.rev = "9efcdf274c35f1ae69d29bd35f43acb9363a0a97"

iced_palace.git = "https://github.com/hecrj/iced_palace.git"
iced_palace.rev = "63cb7d8a0520648ba5c80e2a26cdb14acc212f7f"

reason.git = "https://github.com/hecrj/reason.git"
reason.rev = "d3d81d9de38a7fbd9bb95a9fe0111d4e295006d4"

# iced.path = "../iced"
# iced_core.path = "../iced/core"
# iced_widget.path = "../iced/widget"
# iced_palace.path = "../iced-rs/palace"
# reason.path = "../reason"
# decoder.path = "../decoder"
