[package]
name = "pick-core"
version = "0.1.0-dev"
edition = "2024"

[dependencies]
decoder = "0.0.3"
dirs = "7"
jiff = "0.2"
reason = "0.2.0-dev"
serde_json = "1"

tokio.version = "1"
tokio.features = ["fs", "process", "rt", "sync"]

[dev-dependencies]
pick-test = { version = "0.1.0-dev", path = "../test" }

tokio.version = "1"
tokio.features = ["macros", "test-util"]
